### ISSUE TITLE
Data must not be longer than 256 bytes

### ISSUE THREAD

**Issue by prayagupa** [prayagupd/enc-dec-scala#1]
```scala
javax.crypto.IllegalBlockSizeException: Data must not be longer than 256 bytes

	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:344)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at com.test.EncrypterDecryptor$.$anonfun$decrypt$1(EncrypterDecryptor.scala:25)
	at scala.Option.map(Option.scala:146)
	at com.test.util.EncrypterDecryptor$.decrypt(EncrypterDecryptor.scala:22)
	at com.test..util.EncrypterDecryptorSpec.decrypts using pkcs#8(EncrypterDecryptorSpec.groovy:17)


```

eg.

```groovy
def "encrypts using x509"() {
        given:
        cryptography.pub = "config/public.pub"

        expect:
        cryptography.encrypt("MIIEogIBAAKCAQEAy+t+ROqolTFO2DUsU2rCp8pHK7f80VJwSyXtMKeK14e8HVme\n" +
                "l/ygqyx5e6rQg4IFVKLalOvWW+QTsyi6c+4gZG6Aanq1E4WkGDoQPpxOOkyfg642\n" +
                "g5ZBUDQ3Bg1GNUpLWKvLdGNk6AUSeuv/eBhGzqdbJmzLdKlY2PH+w36fBZU1ct+a\n" +
                "NYn3Tx/TwxWZPnNwvYmdMMYL4CFrwA7OH3GZmpiY3zKSkpgV8yTFTxKXOptAfE+L\n" +
                "uKngljAuYjKPUj0W27vKutls6W9coZ6D9KK+8m+wGVUOG5UahJGLt5f8+W/Z2jE4\n" +
                "coQJEWmG7DdbDNGBicv5rfrX2I0RyhEVAP67RwIDAQABAoIBAAusp8X6STyBXioy\n" +
                "oR8Fda91fS2bkvXI6nTi7vliHafasjItJRZlSLOa8Rg/3N9DAL7ZqK50BnGhrcsD5Sq\n" +
                "OEJ614/oY6G09LjxZbudV2C+QhxEVr2LM8PEzmhxFNVb3TEf18Bz1WoMZrKB19UB\n" +
                "vdZ6TVN3cVh50gwTxeplsFgw35nKHsP2iUBueYhicXU1Dv05FVmAu3Z0LnHsahI4\n" +
                "B40kGV8HhSCY3Q3Il15CcRMUVANU3UR+xaZNOupe7u5lXyUZCjbzhuOUmSKfezcH\n" +
                "QJWEqSw8hn9CLP+teMtuQu5nGK6Cy9lmMsbl94Py+nKoEhtTnRQKXBIyROVEGJ4j\n" +
                "2LsMXAECgYEA++hNnVlh7uNeo1y2Z+x9//2MsYLu9OW1LOvFcdqC46GWyaSolw2H\n" +
                "/FS2ocqSXdbtI1/K3Wog8D8HLzeLIRgsbphW/hzOIn9bRCL98fGW8FdTBCfbTPql\n" +
                "Wc460UVKjGUqgD7+hoGksPA8JJ/sJ4Na4k1ju6DeeXTjEOxOM8K5Q4cCgYEAzzub\n" +
                "dQQFgsR0pTvlurd6/wnOuyeWWJvMCoWKvZ9LD0cAbycGmETQbk2Fp8fREhypKQb0\n" +
                "bqSU3UNiOKmKqzFRqM9IkBb7r3LFGJioyNEEQSvq0EGrIrU8ry8IyN2x7+x1xNnU\n" +
                "hni8hMIH1IpZEXaDsdF14X42oY9Dh4llni4YOkECgYB3b8hE/5koa9N2P0IY+g8v\n" +
                "rabkj0D/Cl6hgtQlzEXc6csdVraVloTvFjuDcyzAkn//lksibvHMLlcaxQ3OK6GxA\n" +
                "r6gnab7uqlW6c6DV8wbuw2iQAtm+oOR/NQG8MU9MS7cgAT4qxhMw9WZ+sviEL4qK\n" +
                "28iasIZrLdlvL6tQbVXrxwKBgBSKc/5FR8aOcoFuTncTeL2O207xvZVK3A6u7fGd\n" +
                "uHLrNr/NvnmZWI+WX4kh5TdGX/4REmllJtxHsZSsOXJ+kPmKkka2AHyDg8XMW+6L\n" +
                "yUAsejnqSGxISpuSrew7DUgayBGbBdXOYeFG2j/W9r0kYild+bFAMWoSKT9l/wyO\n" +
                "xRgBAoGALz5qJBhBBZh2J8PPRIgQtnKKfuM+n5h9542Ai0UJnXlxlHLZ31RAat02\n" +
                "uPkUNmzvkVdTWqRNlMPlg6jkS9jPj7uuem0JpTA7VZlSXeg/wIKphDYmtGhnYuRQ\n" +
                "IIoFieq+JQGzr4CJrpP6SXz6+qTmzE5i2MQ+T8oIFldGyrdx48I=").nonEmpty()
    }
```

error

```
javax.crypto.IllegalBlockSizeException: Data must not be longer than 214 bytes
```

This is what `com.sun.crypto.provider.RSACipher` look like, 

```scala
        if (this.bufOfs > this.buffer.length) {
            throw new IllegalBlockSizeException("Data must not be longer than " + this.buffer.length + " bytes");
        } 
```

Input has 1612 bytes > (256-11 = 245)

Simply because the RSA algo size is 2048 bits = 256 bytes. Verify using `openssl rsa -text -noout -in private.pem `

Either increase the RSA key size; (the RSA key size of 1024 is increasingly under threat) try to use a key size of 2048 at the bare minimum (allowing 256 - 11 = 245 bytes of storage). (11 for padding)

https://stackoverflow.com/a/10007285/432903

Padding(11 bits) is used for `PKCS1Padding` or ... not `NoPadding`. 

Both PKCS#1v1.5 padding and no padding are insecure. Use OAEP padding (which reduces the block size by more than 11 bytes)

https://stackoverflow.com/a/10007597/432903

**Comment by prayagupa** [comment]
https://en.wikipedia.org/wiki/Ring_(mathematics)
